[package]
name = "ratatui-bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
crossterm = "0.27"
libc = "0.2"
ratatui = "0.26"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

